namespace back.Contracts;

public record ImportarNfeResponse(
    long EntradaCompraId,
    string ChaveNfe,
    string NumeroNfe,
    string Serie,
    string Modelo,
    DateTime? DataEmissao,
    DateTime? DataEntrada,
    string NaturezaOperacao,
    string FornecedorNome,
    string FornecedorDocumento,
    decimal ValorProdutos,
    decimal ValorFrete,
    decimal ValorSeguro,
    decimal ValorDesconto,
    decimal ValorOutrasDespesas,
    decimal ValorTotal,
    int TotalItens,
    int ProdutosIdentificados,
    int ProdutosPendentes,
    IReadOnlyCollection<ImportarNfeItemResponse> Itens);

public record ImportarNfeItemResponse(
    int NumeroItem,
    string CodigoFornecedor,
    string? Ean,
    string DescricaoXml,
    string? Ncm,
    string? Cest,
    string? Cfop,
    string UnidadeComercial,
    decimal QuantidadeComercial,
    decimal ValorUnitarioComercial,
    string UnidadeTributavel,
    decimal QuantidadeTributavel,
    decimal ValorUnitarioTributavel,
    decimal ValorProduto,
    decimal ValorFrete,
    decimal ValorSeguro,
    decimal ValorDesconto,
    decimal ValorOutrasDespesas,
    decimal QuantidadeRecebida,
    decimal CustoUnitario,
    bool ProdutoIdentificado,
    int? ProdutoId);
